#include <Arduino.h>
#define STAT_LED_OFF HIGH
#define STAT_LED_ON LOW

//MAGIC-Home RGBWW module
#define STAT_LED_GN 2 //green onboard LED
#define LED_PIN_R 14
#define LED_PIN_G 12
#define LED_PIN_B 13

const unsigned long MIN_CYCLE_TIME = 5000; //ms

#define GO_BELEUCHTUNG_SCHALTEN_EIN_AUS 1
#define GO_BELEUCHTUNG_HELLIGKEIT_ABSOLUT 2
#define GO_BELEUCHTUNG_HELLIGKEIT_RELATIV 3
#define GO_BELEUCHTUNG_SAETTIGUNG_ABSOLUT 4
#define GO_BELEUCHTUNG_SAETTIGUNG_RELATIV 5
#define GO_BELEUCHTUNG_FARBTON_ABSOLUT 6
#define GO_BELEUCHTUNG_FARBTON_RELATIV 7
#define GO_BELEUCHTUNG_FARBE_RGB_ABSOLUT 8
#define GO_BELEUCHTUNG_FARBE_HSV_ABSOLUT 9
#define GO_BELEUCHTUNG_STATUS 10
#define GO_BELEUCHTUNG_STATUS_HELLIGKEIT 11
#define GO_BELEUCHTUNG_STATUS_SAETTIGUNG 12
#define GO_BELEUCHTUNG_STATUS_FARBTON 13
#define GO_BELEUCHTUNG_STATUS_FARBE_RGB 14
#define GO_BELEUCHTUNG_STATUS_FARBE_HSV 15
#define GO_ZENTRAL_SZENE 16
#define GO_ZENTRAL_TAG_NACHT 17
#define AMOUNT_OF_GA 17